spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
    data: classpath:data.sql
    schema: classpath:schema.sql

management:
  endpoints:
    web:
      exposure:
        include: "*"
